#!/usr/bin/env bash
# find the error in the configuration of Nginix (sites-available, sites-enabled)
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
